export const galleryList = [
  {
    id: "1",
    type: "img",
    url: require("../assets/images/gallery/img/-aLu8NqP1K4.jpg"),
    countLike: 0,
  },
  {
    id: "2",
    type: "video",
    url: require("../assets/images/gallery/video/6107660225276.mp4"),
    countLike: 0,
  },
  {
    id: "3",
    type: "img",
    url: require("../assets/images/gallery/img/0KV5o-2HasA.jpg"),
    countLike: 0,
  },
  {
    id: "4",
    type: "img",
    url: require("../assets/images/gallery/img/5-mOaE-1VoY.jpg"),
    countLike: 0,
  },
  {
    id: "5",

    type: "img",
    url: require("../assets/images/gallery/img/1ZUMMYH9Y4A.jpg"),
    countLike: 0,
  },
  {
    id: "6",
    type: "video",
    url: require("../assets/images/gallery/video/Video.mp4"),
    countLike: 0,
  },
  {
    id: "7",
    type: "img",
    url: require("../assets/images/gallery/img/51HUlf-i1U4.jpg"),
    countLike: 0,
  },
  {
    id: "8",
    type: "img",
    url: require("../assets/images/gallery/img/6PjCO4PVTck.jpg"),
    countLike: 0,
  },
  {
    id: "9",
    type: "img",
    url: require("../assets/images/gallery/img/7shHoNiHpeY.jpg"),
    countLike: 0,
  },
  {
    id: "10",
    type: "img",
    url: require("../assets/images/gallery/img/8wy2nlyKNDs.jpg"),
    countLike: 0,
  },
  {
    id: "11",
    type: "img",
    url: require("../assets/images/gallery/img/C3pp4GZmEuE.jpg"),
    countLike: 0,
  },
  {
    id: "12",
    type: "img",
    url: require("../assets/images/gallery/img/FQ0K2Yncf_g.jpg"),
    countLike: 0,
  },
  {
    id: "13",
    type: "video",
    url: require("../assets/images/gallery/video/baza.mp4"),
    countLike: 0,
  },
  {
    id: "14",
    type: "img",
    url: require("../assets/images/gallery/img/FV8lBNUthtA.jpg"),
    countLike: 0,
  },
  {
    id: "15",
    type: "img",
    url: require("../assets/images/gallery/img/HnRCB5J1zxs.jpg"),
    countLike: 0,
  },
  {
    id: "16",
    type: "img",
    url: require("../assets/images/gallery/img/I4sM3YvLzw4.jpg"),
    countLike: 0,
  },
  {
    id: "17",
    type: "img",
    url: require("../assets/images/gallery/img/KiTXpE0q26A.jpg"),
    countLike: 0,
  },
  {
    id: "18",
    type: "img",
    url: require("../assets/images/gallery/img/NFxqYZcGOC4.jpg"),
    countLike: 0,
  },
  {
    id: "19",
    type: "video",
    url: require("../assets/images/gallery/video/dashinit.mp4"),
    countLike: 0,
  },
  {
    id: "20",
    type: "img",
    url: require("../assets/images/gallery/img/O9mQJQA9mAA.jpg"),
    countLike: 0,
  },
  {
    id: "21",
    type: "img",
    url: require("../assets/images/gallery/img/S3cMa2FXvAI.jpg"),
    countLike: 0,
  },
  {
    id: "22",
    type: "img",
    url: require("../assets/images/gallery/img/TurfCaHXm4E.jpg"),
    countLike: 0,
  },
  {
    id: "23",
    type: "img",
    url: require("../assets/images/gallery/img/VLPZdM0NsNM.jpg"),
    countLike: 0,
  },
  {
    id: "24",
    type: "img",
    url: require("../assets/images/gallery/img/WUXVZR8LiBs.jpg"),
    countLike: 0,
  },
  {
    id: "25",
    type: "img",
    url: require("../assets/images/gallery/img/Ziqytzq4BDU.jpg"),
    countLike: 0,
  },
  {
    id: "26",
    type: "img",
    url: require("../assets/images/gallery/img/_-1QWsgfVQs.jpg"),
    countLike: 0,
  },
  {
    id: "27",
    type: "img",
    url: require("../assets/images/gallery/img/dRwLU5s6mVY.jpg"),
    countLike: 0,
  },
  {
    id: "28",
    type: "img",
    url: require("../assets/images/gallery/img/eG2dCTC28y4.jpg"),
    countLike: 0,
  },
  {
    id: "29",
    type: "img",
    url: require("../assets/images/gallery/img/f7fJ1Dkj-jk.jpg"),
    countLike: 0,
  },
  {
    id: "30",
    type: "video",
    url: require("../assets/images/gallery/video/l.mp4"),
    countLike: 0,
  },
  {
    id: "31",
    type: "img",
    url: require("../assets/images/gallery/img/iHxzIreuLn0.jpg"),
    countLike: 0,
  },
  {
    id: "32",
    type: "img",
    url: require("../assets/images/gallery/img/iva6EaCGX6s.jpg"),
    countLike: 0,
  },
  {
    id: "33",
    type: "img",
    url: require("../assets/images/gallery/img/jiK5UQND-Ic.jpg"),
    countLike: 0,
  },
  {
    id: "34",
    type: "img",
    url: require("../assets/images/gallery/img/kRrtAaeyybM.jpg"),
    countLike: 0,
  },
  {
    id: "35",
    type: "img",
    url: require("../assets/images/gallery/img/mnFQXVbglpE.jpg"),
    countLike: 0,
  },
  {
    id: "36",
    type: "img",
    url: require("../assets/images/gallery/img/npUEEwDxooI.jpg"),
    countLike: 0,
  },
  {
    id: "37",
    type: "img",
    url: require("../assets/images/gallery/img/pPuCRhWGFF0.jpg"),
    countLike: 0,
  },
  {
    id: "38",
    type: "img",
    url: require("../assets/images/gallery/img/rZEc2a_uwhM.jpg"),
    countLike: 0,
  },
  {
    id: "39",
    type: "img",
    url: require("../assets/images/gallery/img/sAvgALXO4v8.jpg"),
    countLike: 0,
  },
  {
    id: "40",
    type: "img",
    url: require("../assets/images/gallery/img/tf_BM6J7eSA.jpg"),
    countLike: 0,
  },
  {
    id: "41",
    type: "img",
    url: require("../assets/images/gallery/img/uPAfzVB7Q24.jpg"),
    countLike: 0,
  },
  {
    id: "42",
    type: "img",
    url: require("../assets/images/gallery/img/uTwHUHRuyXU.jpg"),
    countLike: 0,
  },
  {
    id: "43",
    type: "img",
    url: require("../assets/images/gallery/img/w5iQkg_iASE.jpg"),
    countLike: 0,
  },
  {
    id: "44",
    type: "img",
    url: require("../assets/images/gallery/img/xGl73guAIaY.jpg"),
    countLike: 0,
  },
  {
    id: "45",
    type: "img",
    url: require("../assets/images/gallery/img/zSO7t9k4eLg.jpg"),
    countLike: 0,
  },
  {
    id: "46",
    type: "video",
    url: require("../assets/images/gallery/video/5775710882418.mp4"),
    countLike: 0,
  },
];
